### ISSUE TITLE
Add page numbers to table of contents page

### ISSUE THREAD

**Issue by tanga94** [rfortherestofus/pagedreport#50]
Is there any way to add the page numbers to the table of contents? I've tried adding the following CSS to my Rmarkdown document however it doesn't work

```
.toc a::after,
.toc2 a::after {
  content: "p. " target-counter(attr(href), page);
  float: right;
}
```

Here is my YAML

```
---
title: "Document Title"
subtitle: "Document Subtitle"
author: "My Name"
date: "`r format(Sys.time(), '%B %Y')`"
output: 
  pagedreport::paged_windmill:
    front_img: Cover Page and Logo/cover.png
    logo: Cover Page and Logo/logo.svg
    logo_to_white: TRUE
    img_to_dark: TRUE
    toc: TRUE
    number_sections: TRUE
knit: pagedown::chrome_print
toc-title: "Table of Contents"
main-color: "#6d1d26"
google-font: FALSE
main-font: "Arial"
header-font: "Arial"
---

```
